# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
#  routing_loader:
#    default_format: json
    param_fetcher_listener:  true
    body_listener: true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    allowed_methods_listener:  true
    routing_loader: true
    view:
        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
            - { path: ^/informer, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
            - { path: ^/informertype, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
            - { path: ^/servicedatatype, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
            - { path: ^/servicedata, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
