#index:
#  path: /
#  controller: App\Controller\DefaultController::index


app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

api:
  path: /api
  controller: App\Controller\InformerApiController::index

informer:
  type:     rest
  resource: App\Controller\InformerController

service_data_type:
  type:     rest
  resource: App\Controller\ServiceDataTypeController

service_data:
  type:     rest
  resource: App\Controller\ServiceDataController

informer_type:
  type:     rest
  resource: App\Controller\InformerTypeController